//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseAssignment
    {
        public int Id { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> CustomerCaseId { get; set; }
        public Nullable<System.DateTime> CompeletionDate { get; set; }
        public string Remark { get; set; }
    
        public virtual CustomerCas CustomerCas { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
